// Auto-generated by build.cmd on every build -- do not edit by hand.
// Stamps the exe with today's date as its version: 1.YY.MMDD.0.
using System.Reflection;
[assembly: AssemblyVersion("1.26.0630.0")]
[assembly: AssemblyFileVersion("1.26.0630.0")]
[assembly: AssemblyInformationalVersion("1.26.0630.0")]
[assembly: AssemblyProduct("WgSharp")]
[assembly: AssemblyTitle("WgSharp")]
[assembly: AssemblyDescription("A from-scratch WireGuard client for Windows")]
[assembly: AssemblyCopyright("Copyright \u00A9 2026 inteliboy")]
